{% set version = "11.1.0" %}

package:
  name: django-bootstrap3
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/django-bootstrap3/django-bootstrap3-{{ version }}.tar.gz
  sha256: c417b25328fb8e97cb89e1f07d35632602d702e6eaca863328e833939d0d1743

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.8

test:
  requires:
    - python {{ python_min }}
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['bootstrap3']); django.setup(); import bootstrap3;"

about:
  home: https://github.com/dyve/django-bootstrap3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Bootstrap 3 integration with Django.'
  description: |
    Write Django as usual, and let django-bootstrap3 make template output 
    into Bootstrap 3 code.
  doc_url: http://django-bootstrap3.readthedocs.org/
  dev_url: https://github.com/dyve/django-bootstrap3

extra:
  recipe-maintainers:
    - xmnlab
